services:
  - type: web
    name: magicwebb
    runtime: go
    rootDir: backend
    buildCommand: go build -o ../bin/magicwebb ./cmd/server
    startCommand: ../bin/magicwebb
    port: 8080
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: POSTGRES_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RPC_URL
        value: https://coston2-api.flare.network/ext/C/rpc
      - key: CHAIN_ID
        value: "114"
      - key: MARKETPLACE_ADDR
        value: "0xEC47a481513DA81FF59A6c4002A98803039994E5"  # MARKETPLACE
      - key: AUCTION_ADDR
        value: "0xf62e931D807f87eBd90Cc3254b0a34a76c326331"  # AUCTION
      - key: OFFERBOOK_ADDR
        value: "0x7e88e86F61E6AD80abD828B6bCEDAA86311736f0"  # OFFERBOOK
      - key: HTTP_ADDR
        value: ":8080"
      - key: FRONTEND_URL
        value: https://magicwebb.onrender.com
      - key: SIWE_DOMAIN
        value: magicwebb.onrender.com
      - key: ENV
        value: production
      - key: INDEX_FROM_BLOCK
        value: "30437062"
      - key: GETLOGS_CHUNK
        value: "30"
      - key: GETLOGS_BLOCK_CAP
        value: "30"
      - key: KEEPER_KEY
        sync: false
