// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: marketplace/v1/marketplace.proto

package marketplacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`          // hex-encoded contract address
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"` // decimal uint256 token ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_v1_marketplace_proto_rawDescGZIP(), []int{0}
}

func (x *GetListingRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetListingRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Seller        string                 `protobuf:"bytes,3,opt,name=seller,proto3" json:"seller,omitempty"`
	PriceWei      string                 `protobuf:"bytes,4,opt,name=price_wei,json=priceWei,proto3" json:"price_wei,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Standard      string                 `protobuf:"bytes,6,opt,name=standard,proto3" json:"standard,omitempty"` // "erc721" | "erc1155"
	ExpiresAtMs   int64                  `protobuf:"varint,7,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	ListedAtMs    int64                  `protobuf:"varint,8,opt,name=listed_at_ms,json=listedAtMs,proto3" json:"listed_at_ms,omitempty"`
	TxHash        string                 `protobuf:"bytes,9,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`                         // denormalised from nft_metadata / nft_tokens
	ImageUri      string                 `protobuf:"bytes,11,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"` // denormalised metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingResponse) Reset() {
	*x = GetListingResponse{}
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingResponse) ProtoMessage() {}

func (x *GetListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingResponse.ProtoReflect.Descriptor instead.
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_v1_marketplace_proto_rawDescGZIP(), []int{1}
}

func (x *GetListingResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetListingResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *GetListingResponse) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *GetListingResponse) GetPriceWei() string {
	if x != nil {
		return x.PriceWei
	}
	return ""
}

func (x *GetListingResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetListingResponse) GetStandard() string {
	if x != nil {
		return x.Standard
	}
	return ""
}

func (x *GetListingResponse) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *GetListingResponse) GetListedAtMs() int64 {
	if x != nil {
		return x.ListedAtMs
	}
	return 0
}

func (x *GetListingResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetListingResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListingResponse) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

type GetAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionRequest) Reset() {
	*x = GetAuctionRequest{}
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionRequest) ProtoMessage() {}

func (x *GetAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionRequest.ProtoReflect.Descriptor instead.
func (*GetAuctionRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_v1_marketplace_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuctionRequest) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

type GetAuctionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuctionId       int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Collection      string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Seller          string                 `protobuf:"bytes,4,opt,name=seller,proto3" json:"seller,omitempty"`
	Standard        string                 `protobuf:"bytes,5,opt,name=standard,proto3" json:"standard,omitempty"`
	ReservePriceWei string                 `protobuf:"bytes,6,opt,name=reserve_price_wei,json=reservePriceWei,proto3" json:"reserve_price_wei,omitempty"`
	HighestBidWei   string                 `protobuf:"bytes,7,opt,name=highest_bid_wei,json=highestBidWei,proto3" json:"highest_bid_wei,omitempty"`
	HighestBidder   string                 `protobuf:"bytes,8,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	MinIncrementBps int32                  `protobuf:"varint,9,opt,name=min_increment_bps,json=minIncrementBps,proto3" json:"min_increment_bps,omitempty"`
	StartsAtMs      int64                  `protobuf:"varint,10,opt,name=starts_at_ms,json=startsAtMs,proto3" json:"starts_at_ms,omitempty"`
	EndsAtMs        int64                  `protobuf:"varint,11,opt,name=ends_at_ms,json=endsAtMs,proto3" json:"ends_at_ms,omitempty"`
	Status          string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"` // "active" | "settled" | "cancelled"
	CreateTx        string                 `protobuf:"bytes,13,opt,name=create_tx,json=createTx,proto3" json:"create_tx,omitempty"`
	Name            string                 `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	ImageUri        string                 `protobuf:"bytes,15,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAuctionResponse) Reset() {
	*x = GetAuctionResponse{}
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionResponse) ProtoMessage() {}

func (x *GetAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionResponse.ProtoReflect.Descriptor instead.
func (*GetAuctionResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_v1_marketplace_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuctionResponse) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *GetAuctionResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetAuctionResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *GetAuctionResponse) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *GetAuctionResponse) GetStandard() string {
	if x != nil {
		return x.Standard
	}
	return ""
}

func (x *GetAuctionResponse) GetReservePriceWei() string {
	if x != nil {
		return x.ReservePriceWei
	}
	return ""
}

func (x *GetAuctionResponse) GetHighestBidWei() string {
	if x != nil {
		return x.HighestBidWei
	}
	return ""
}

func (x *GetAuctionResponse) GetHighestBidder() string {
	if x != nil {
		return x.HighestBidder
	}
	return ""
}

func (x *GetAuctionResponse) GetMinIncrementBps() int32 {
	if x != nil {
		return x.MinIncrementBps
	}
	return 0
}

func (x *GetAuctionResponse) GetStartsAtMs() int64 {
	if x != nil {
		return x.StartsAtMs
	}
	return 0
}

func (x *GetAuctionResponse) GetEndsAtMs() int64 {
	if x != nil {
		return x.EndsAtMs
	}
	return 0
}

func (x *GetAuctionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAuctionResponse) GetCreateTx() string {
	if x != nil {
		return x.CreateTx
	}
	return ""
}

func (x *GetAuctionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAuctionResponse) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

type GetOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferRequest) Reset() {
	*x = GetOfferRequest{}
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferRequest) ProtoMessage() {}

func (x *GetOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferRequest.ProtoReflect.Descriptor instead.
func (*GetOfferRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_v1_marketplace_proto_rawDescGZIP(), []int{4}
}

func (x *GetOfferRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

type GetOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Bidder        string                 `protobuf:"bytes,2,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	TokenId       string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	AmountWei     string                 `protobuf:"bytes,5,opt,name=amount_wei,json=amountWei,proto3" json:"amount_wei,omitempty"` // principal_wei: escrowed amount (fee excluded)
	FeeWei        string                 `protobuf:"bytes,6,opt,name=fee_wei,json=feeWei,proto3" json:"fee_wei,omitempty"`
	Units         int64                  `protobuf:"varint,7,opt,name=units,proto3" json:"units,omitempty"`
	Standard      string                 `protobuf:"bytes,8,opt,name=standard,proto3" json:"standard,omitempty"`
	ExpiresAtMs   int64                  `protobuf:"varint,9,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "accepted" | "cancelled" | "expired"
	MakeTx        string                 `protobuf:"bytes,11,opt,name=make_tx,json=makeTx,proto3" json:"make_tx,omitempty"`
	CreatedAtMs   int64                  `protobuf:"varint,12,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferResponse) Reset() {
	*x = GetOfferResponse{}
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferResponse) ProtoMessage() {}

func (x *GetOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferResponse.ProtoReflect.Descriptor instead.
func (*GetOfferResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_v1_marketplace_proto_rawDescGZIP(), []int{5}
}

func (x *GetOfferResponse) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *GetOfferResponse) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

func (x *GetOfferResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetOfferResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *GetOfferResponse) GetAmountWei() string {
	if x != nil {
		return x.AmountWei
	}
	return ""
}

func (x *GetOfferResponse) GetFeeWei() string {
	if x != nil {
		return x.FeeWei
	}
	return ""
}

func (x *GetOfferResponse) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *GetOfferResponse) GetStandard() string {
	if x != nil {
		return x.Standard
	}
	return ""
}

func (x *GetOfferResponse) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *GetOfferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOfferResponse) GetMakeTx() string {
	if x != nil {
		return x.MakeTx
	}
	return ""
}

func (x *GetOfferResponse) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_v1_marketplace_proto_rawDescGZIP(), []int{6}
}

func (x *GetTokenRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUri      string                 `protobuf:"bytes,5,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	AnimationUri  string                 `protobuf:"bytes,6,opt,name=animation_uri,json=animationUri,proto3" json:"animation_uri,omitempty"`
	MetadataUri   string                 `protobuf:"bytes,7,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	FetchedAtMs   int64                  `protobuf:"varint,8,opt,name=fetched_at_ms,json=fetchedAtMs,proto3" json:"fetched_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_v1_marketplace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_v1_marketplace_proto_rawDescGZIP(), []int{7}
}

func (x *GetTokenResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *GetTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTokenResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTokenResponse) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *GetTokenResponse) GetAnimationUri() string {
	if x != nil {
		return x.AnimationUri
	}
	return ""
}

func (x *GetTokenResponse) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *GetTokenResponse) GetFetchedAtMs() int64 {
	if x != nil {
		return x.FetchedAtMs
	}
	return 0
}

var File_marketplace_v1_marketplace_proto protoreflect.FileDescriptor

const file_marketplace_v1_marketplace_proto_rawDesc = "" +
	"\n" +
	" marketplace/v1/marketplace.proto\x12\x0emarketplace.v1\"N\n" +
	"\x11GetListingRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"\xc8\x02\n" +
	"\x12GetListingResponse\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12\x16\n" +
	"\x06seller\x18\x03 \x01(\tR\x06seller\x12\x1b\n" +
	"\tprice_wei\x18\x04 \x01(\tR\bpriceWei\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bstandard\x18\x06 \x01(\tR\bstandard\x12\"\n" +
	"\rexpires_at_ms\x18\a \x01(\x03R\vexpiresAtMs\x12 \n" +
	"\flisted_at_ms\x18\b \x01(\x03R\n" +
	"listedAtMs\x12\x17\n" +
	"\atx_hash\x18\t \x01(\tR\x06txHash\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x1b\n" +
	"\timage_uri\x18\v \x01(\tR\bimageUri\"2\n" +
	"\x11GetAuctionRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\"\xef\x03\n" +
	"\x12GetAuctionResponse\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x16\n" +
	"\x06seller\x18\x04 \x01(\tR\x06seller\x12\x1a\n" +
	"\bstandard\x18\x05 \x01(\tR\bstandard\x12*\n" +
	"\x11reserve_price_wei\x18\x06 \x01(\tR\x0freservePriceWei\x12&\n" +
	"\x0fhighest_bid_wei\x18\a \x01(\tR\rhighestBidWei\x12%\n" +
	"\x0ehighest_bidder\x18\b \x01(\tR\rhighestBidder\x12*\n" +
	"\x11min_increment_bps\x18\t \x01(\x05R\x0fminIncrementBps\x12 \n" +
	"\fstarts_at_ms\x18\n" +
	" \x01(\x03R\n" +
	"startsAtMs\x12\x1c\n" +
	"\n" +
	"ends_at_ms\x18\v \x01(\x03R\bendsAtMs\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1b\n" +
	"\tcreate_tx\x18\r \x01(\tR\bcreateTx\x12\x12\n" +
	"\x04name\x18\x0e \x01(\tR\x04name\x12\x1b\n" +
	"\timage_uri\x18\x0f \x01(\tR\bimageUri\",\n" +
	"\x0fGetOfferRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\"\xe3\x02\n" +
	"\x10GetOfferResponse\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12\x16\n" +
	"\x06bidder\x18\x02 \x01(\tR\x06bidder\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x1d\n" +
	"\n" +
	"amount_wei\x18\x05 \x01(\tR\tamountWei\x12\x17\n" +
	"\afee_wei\x18\x06 \x01(\tR\x06feeWei\x12\x14\n" +
	"\x05units\x18\a \x01(\x03R\x05units\x12\x1a\n" +
	"\bstandard\x18\b \x01(\tR\bstandard\x12\"\n" +
	"\rexpires_at_ms\x18\t \x01(\x03R\vexpiresAtMs\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x17\n" +
	"\amake_tx\x18\v \x01(\tR\x06makeTx\x12\"\n" +
	"\rcreated_at_ms\x18\f \x01(\x03R\vcreatedAtMs\"L\n" +
	"\x0fGetTokenRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"\x8c\x02\n" +
	"\x10GetTokenResponse\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_uri\x18\x05 \x01(\tR\bimageUri\x12#\n" +
	"\ranimation_uri\x18\x06 \x01(\tR\fanimationUri\x12!\n" +
	"\fmetadata_uri\x18\a \x01(\tR\vmetadataUri\x12\"\n" +
	"\rfetched_at_ms\x18\b \x01(\x03R\vfetchedAtMs2\xdc\x02\n" +
	"\x12MarketplaceService\x12S\n" +
	"\n" +
	"GetListing\x12!.marketplace.v1.GetListingRequest\x1a\".marketplace.v1.GetListingResponse\x12S\n" +
	"\n" +
	"GetAuction\x12!.marketplace.v1.GetAuctionRequest\x1a\".marketplace.v1.GetAuctionResponse\x12M\n" +
	"\bGetOffer\x12\x1f.marketplace.v1.GetOfferRequest\x1a .marketplace.v1.GetOfferResponse\x12M\n" +
	"\bGetToken\x12\x1f.marketplace.v1.GetTokenRequest\x1a .marketplace.v1.GetTokenResponseBPZNgithub.com/OfficialA1manac/MagicWebb/backend/internal/connectrpc/marketplacev1b\x06proto3"

var (
	file_marketplace_v1_marketplace_proto_rawDescOnce sync.Once
	file_marketplace_v1_marketplace_proto_rawDescData []byte
)

func file_marketplace_v1_marketplace_proto_rawDescGZIP() []byte {
	file_marketplace_v1_marketplace_proto_rawDescOnce.Do(func() {
		file_marketplace_v1_marketplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_v1_marketplace_proto_rawDesc), len(file_marketplace_v1_marketplace_proto_rawDesc)))
	})
	return file_marketplace_v1_marketplace_proto_rawDescData
}

var file_marketplace_v1_marketplace_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_marketplace_v1_marketplace_proto_goTypes = []any{
	(*GetListingRequest)(nil),  // 0: marketplace.v1.GetListingRequest
	(*GetListingResponse)(nil), // 1: marketplace.v1.GetListingResponse
	(*GetAuctionRequest)(nil),  // 2: marketplace.v1.GetAuctionRequest
	(*GetAuctionResponse)(nil), // 3: marketplace.v1.GetAuctionResponse
	(*GetOfferRequest)(nil),    // 4: marketplace.v1.GetOfferRequest
	(*GetOfferResponse)(nil),   // 5: marketplace.v1.GetOfferResponse
	(*GetTokenRequest)(nil),    // 6: marketplace.v1.GetTokenRequest
	(*GetTokenResponse)(nil),   // 7: marketplace.v1.GetTokenResponse
}
var file_marketplace_v1_marketplace_proto_depIdxs = []int32{
	0, // 0: marketplace.v1.MarketplaceService.GetListing:input_type -> marketplace.v1.GetListingRequest
	2, // 1: marketplace.v1.MarketplaceService.GetAuction:input_type -> marketplace.v1.GetAuctionRequest
	4, // 2: marketplace.v1.MarketplaceService.GetOffer:input_type -> marketplace.v1.GetOfferRequest
	6, // 3: marketplace.v1.MarketplaceService.GetToken:input_type -> marketplace.v1.GetTokenRequest
	1, // 4: marketplace.v1.MarketplaceService.GetListing:output_type -> marketplace.v1.GetListingResponse
	3, // 5: marketplace.v1.MarketplaceService.GetAuction:output_type -> marketplace.v1.GetAuctionResponse
	5, // 6: marketplace.v1.MarketplaceService.GetOffer:output_type -> marketplace.v1.GetOfferResponse
	7, // 7: marketplace.v1.MarketplaceService.GetToken:output_type -> marketplace.v1.GetTokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marketplace_v1_marketplace_proto_init() }
func file_marketplace_v1_marketplace_proto_init() {
	if File_marketplace_v1_marketplace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_v1_marketplace_proto_rawDesc), len(file_marketplace_v1_marketplace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_v1_marketplace_proto_goTypes,
		DependencyIndexes: file_marketplace_v1_marketplace_proto_depIdxs,
		MessageInfos:      file_marketplace_v1_marketplace_proto_msgTypes,
	}.Build()
	File_marketplace_v1_marketplace_proto = out.File
	file_marketplace_v1_marketplace_proto_goTypes = nil
	file_marketplace_v1_marketplace_proto_depIdxs = nil
}
