// Package marketplacev1 provides a Connect-RPC server that implements the
// MarketplaceService defined in marketplace.proto. Each handler performs a
// direct DB query and returns the result as a typed Protobuf message —
// no JSON marshal/unmarshal, no manual HTTP status code handling.
//
// The handler is mounted via an adapter in the api package so it works with
// Fiber's fasthttp underpinnings. Clients can call it using Connect-RPC
// (JSON or Protobuf, over HTTP/1.1 or HTTP/2), gRPC, or gRPC-Web.
package marketplacev1

import (
	"context"
	"strings"

	"connectrpc.com/connect"

	"github.com/OfficialA1manac/MagicWebb/backend/internal/db"
)

// Server implements the MarketplaceServiceHandler interface generated by
// protoc-gen-connect-go. It wraps a *db.Q for read queries.
type Server struct {
	q *db.Q
}

// NewServer creates a MarketplaceService handler backed by the given DB.
func NewServer(q *db.Q) *Server {
	return &Server{q: q}
}

// ── GetListing ──────────────────────────────────────────────────────────────

func (s *Server) GetListing(ctx context.Context, req *connect.Request[GetListingRequest]) (*connect.Response[GetListingResponse], error) {
	collection := strings.ToLower(req.Msg.GetCollection())
	tokenID := req.Msg.GetTokenId()

	row, err := s.q.GetListing(ctx, collection, tokenID)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetListingResponse{
		Collection: row.Collection,
		TokenId:    row.TokenID,
		Seller:     row.Seller,
		PriceWei:   row.PriceWei,
		Amount:     row.Amount,
		Standard:   row.Standard,
		TxHash:     row.TxHash,
		Name:       row.Name,
		ImageUri:   row.ImageURI,
	}
	if !row.ExpiresAt.IsZero() {
		res.ExpiresAtMs = row.ExpiresAt.UnixMilli()
	}
	if !row.ListedAt.IsZero() {
		res.ListedAtMs = row.ListedAt.UnixMilli()
	}

	return connect.NewResponse(res), nil
}

// ── GetAuction ──────────────────────────────────────────────────────────────

func (s *Server) GetAuction(ctx context.Context, req *connect.Request[GetAuctionRequest]) (*connect.Response[GetAuctionResponse], error) {
	auctionID := req.Msg.GetAuctionId()

	row, err := s.q.GetAuction(ctx, auctionID)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetAuctionResponse{
		AuctionId:       row.AuctionID,
		Collection:      row.Collection,
		TokenId:         row.TokenID,
		Seller:          row.Seller,
		Standard:        row.Standard,
		ReservePriceWei: row.ReservePriceWei,
		HighestBidWei:   row.HighestBidWei,
		HighestBidder:   row.HighestBidder,
		MinIncrementBps: int32(row.MinIncrementBps),
		Status:          row.Status,
		CreateTx:        row.CreateTx,
		Name:            row.Name,
		ImageUri:        row.ImageURI,
	}
	if !row.StartsAt.IsZero() {
		res.StartsAtMs = row.StartsAt.UnixMilli()
	}
	if !row.EndsAt.IsZero() {
		res.EndsAtMs = row.EndsAt.UnixMilli()
	}

	return connect.NewResponse(res), nil
}

// ── GetOffer ────────────────────────────────────────────────────────────────

func (s *Server) GetOffer(ctx context.Context, req *connect.Request[GetOfferRequest]) (*connect.Response[GetOfferResponse], error) {
	offerID := req.Msg.GetOfferId()

	row, err := s.q.GetOffer(ctx, offerID)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetOfferResponse{
		OfferId:    row.OfferID,
		Bidder:     row.Bidder,
		Collection: row.Collection,
		TokenId:    row.TokenID,
		AmountWei:  row.AmountWei,
		FeeWei:     row.FeeWei,
		Units:      row.Units,
		Standard:   row.Standard,
		Status:     row.Status,
		MakeTx:     row.MakeTx,
	}
	if !row.ExpiresAt.IsZero() {
		res.ExpiresAtMs = row.ExpiresAt.UnixMilli()
	}
	if !row.CreatedAt.IsZero() {
		res.CreatedAtMs = row.CreatedAt.UnixMilli()
	}

	return connect.NewResponse(res), nil
}

// ── GetToken ────────────────────────────────────────────────────────────────

func (s *Server) GetToken(ctx context.Context, req *connect.Request[GetTokenRequest]) (*connect.Response[GetTokenResponse], error) {
	collection := strings.ToLower(req.Msg.GetCollection())
	tokenID := req.Msg.GetTokenId()

	name, desc, imageURI, animURI, metaURI, fetchedAt, err := s.q.GetTokenFullMetadata(ctx, collection, tokenID)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetTokenResponse{
		Collection:   collection,
		TokenId:      tokenID,
		Name:         name,
		Description:  desc,
		ImageUri:     imageURI,
		AnimationUri: animURI,
		MetadataUri:  metaURI,
	}
	if !fetchedAt.IsZero() {
		res.FetchedAtMs = fetchedAt.UnixMilli()
	}

	return connect.NewResponse(res), nil
}

// ── Helpers ─────────────────────────────────────────────────────────────────

func isNotFound(err error) bool {
	if err == nil {
		return false
	}
	s := err.Error()
	return strings.Contains(s, "not found") || strings.Contains(s, "no rows")
}
