// Package marketplacev1 provides a Connect-RPC server that implements the
// MarketplaceService defined in marketplace.proto. Each handler performs a
// direct DB query and returns the result as a typed Protobuf message —
// no JSON marshal/unmarshal, no manual HTTP status code handling.
//
// The handler is mounted via an adapter in the api package so it works with
// Fiber's fasthttp underpinnings. Clients can call it using Connect-RPC
// (JSON or Protobuf, over HTTP/1.1 or HTTP/2), gRPC, or gRPC-Web.
package marketplacev1

import (
	"context"
	"fmt"
	"strings"

	"connectrpc.com/connect"

	"github.com/OfficialA1manac/MagicWebb/backend/internal/db"
	"github.com/OfficialA1manac/MagicWebb/backend/internal/sse"
)

// Server implements the MarketplaceServiceHandler interface generated by
// protoc-gen-connect-go. It wraps a *db.Q for read queries and an optional
// SSE Broadcaster for streaming subscription handlers.
type Server struct {
	q     *db.Q
	bcast *sse.Broadcaster
}

// NewServer creates a MarketplaceService handler backed by the given DB.
// bcast is optional — when nil, streaming subscription RPCs return
// Unavailable errors to clients.
func NewServer(q *db.Q, bcast *sse.Broadcaster) *Server {
	return &Server{q: q, bcast: bcast}
}

// ── GetListing ──────────────────────────────────────────────────────────────

func (s *Server) GetListing(ctx context.Context, req *connect.Request[GetListingRequest]) (*connect.Response[GetListingResponse], error) {
	collection := strings.ToLower(req.Msg.GetCollection())
	tokenID := req.Msg.GetTokenId()

	row, err := s.q.GetListing(ctx, collection, tokenID)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetListingResponse{
		Collection: row.Collection,
		TokenId:    row.TokenID,
		Seller:     row.Seller,
		PriceWei:   row.PriceWei,
		Amount:     row.Amount,
		Standard:   row.Standard,
		TxHash:     row.TxHash,
		Name:       row.Name,
		ImageUri:   row.ImageURI,
	}
	if !row.ExpiresAt.IsZero() {
		res.ExpiresAtMs = row.ExpiresAt.UnixMilli()
	}
	if !row.ListedAt.IsZero() {
		res.ListedAtMs = row.ListedAt.UnixMilli()
	}

	return connect.NewResponse(res), nil
}

// ── GetAuction ──────────────────────────────────────────────────────────────

func (s *Server) GetAuction(ctx context.Context, req *connect.Request[GetAuctionRequest]) (*connect.Response[GetAuctionResponse], error) {
	auctionID := req.Msg.GetAuctionId()

	row, err := s.q.GetAuction(ctx, auctionID)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetAuctionResponse{
		AuctionId:       row.AuctionID,
		Collection:      row.Collection,
		TokenId:         row.TokenID,
		Seller:          row.Seller,
		Standard:        row.Standard,
		ReservePriceWei: row.ReservePriceWei,
		HighestBidWei:   row.HighestBidWei,
		HighestBidder:   row.HighestBidder,
		MinIncrementBps: int32(row.MinIncrementBps),
		Status:          row.Status,
		CreateTx:        row.CreateTx,
		Name:            row.Name,
		ImageUri:        row.ImageURI,
	}
	if !row.StartsAt.IsZero() {
		res.StartsAtMs = row.StartsAt.UnixMilli()
	}
	if !row.EndsAt.IsZero() {
		res.EndsAtMs = row.EndsAt.UnixMilli()
	}

	return connect.NewResponse(res), nil
}

// ── GetOffer ────────────────────────────────────────────────────────────────

func (s *Server) GetOffer(ctx context.Context, req *connect.Request[GetOfferRequest]) (*connect.Response[GetOfferResponse], error) {
	offerID := req.Msg.GetOfferId()

	row, err := s.q.GetOffer(ctx, offerID)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetOfferResponse{
		OfferId:    row.OfferID,
		Bidder:     row.Bidder,
		Collection: row.Collection,
		TokenId:    row.TokenID,
		AmountWei:  row.AmountWei,
		FeeWei:     row.FeeWei,
		Units:      row.Units,
		Standard:   row.Standard,
		Status:     row.Status,
		MakeTx:     row.MakeTx,
	}
	if !row.ExpiresAt.IsZero() {
		res.ExpiresAtMs = row.ExpiresAt.UnixMilli()
	}
	if !row.CreatedAt.IsZero() {
		res.CreatedAtMs = row.CreatedAt.UnixMilli()
	}

	return connect.NewResponse(res), nil
}

// ── GetToken ────────────────────────────────────────────────────────────────

func (s *Server) GetToken(ctx context.Context, req *connect.Request[GetTokenRequest]) (*connect.Response[GetTokenResponse], error) {
	collection := strings.ToLower(req.Msg.GetCollection())
	tokenID := req.Msg.GetTokenId()

	name, desc, imageURI, animURI, metaURI, fetchedAt, err := s.q.GetTokenFullMetadata(ctx, collection, tokenID)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetTokenResponse{
		Collection:   collection,
		TokenId:      tokenID,
		Name:         name,
		Description:  desc,
		ImageUri:     imageURI,
		AnimationUri: animURI,
		MetadataUri:  metaURI,
	}
	if !fetchedAt.IsZero() {
		res.FetchedAtMs = fetchedAt.UnixMilli()
	}

	return connect.NewResponse(res), nil
}

// ── ListCollections (server-streaming) ───────────────────────────────────────

func (s *Server) ListCollections(ctx context.Context, req *connect.Request[ListCollectionsRequest], stream *connect.ServerStream[Collection]) error {
	limit := int(req.Msg.GetLimit())
	if limit <= 0 || limit > 200 {
		limit = 50
	}

	rows, err := s.q.ListCollections(ctx, limit)
	if err != nil {
		return connect.NewError(connect.CodeInternal, err)
	}

	// Collect addresses for batch stats (single round-trip after streaming basics).
	cols := make([]*Collection, 0, len(rows))
	addrs := make([]string, 0, len(rows))
	for i := range rows {
		cols = append(cols, &Collection{
			Address:     rows[i].Address,
			Name:        rows[i].Name,
			Symbol:      rows[i].Symbol,
			Standard:    rows[i].Standard,
			DeployBlock: int64(rows[i].DeployBlock),
			Verified:    rows[i].Verified,
		})
		addrs = append(addrs, rows[i].Address)
	}

	// Batch-fill stats: one round-trip for floor + listed count + volume.
	if stats, err := s.q.GetCollectionStatsBatch(ctx, addrs); err == nil {
		for i, c := range cols {
			if s, ok := stats[c.Address]; ok {
				cols[i].FloorPriceWei = s.FloorPriceWei
				cols[i].Volume_24HWei = s.Volume24hWei
				cols[i].ListedCount = int32(s.ListedCount)
			}
		}
	}

	// Stream each collection to the client as it's ready.
	for _, c := range cols {
		if err := stream.Send(c); err != nil {
			return err
		}
	}
	return nil
}

// ── GetCollection ─────────────────────────────────────────────────────────────

func (s *Server) GetCollection(ctx context.Context, req *connect.Request[GetCollectionRequest]) (*connect.Response[GetCollectionResponse], error) {
	address := strings.ToLower(req.Msg.GetAddress())

	row, err := s.q.GetCollection(ctx, address)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := &GetCollectionResponse{
		Address:     row.Address,
		Name:        row.Name,
		Symbol:      row.Symbol,
		Standard:    row.Standard,
		DeployBlock: int64(row.DeployBlock),
		Verified:    row.Verified,
	}

	// Best-effort stats via existing consolidated helper (3 sub-queries, one shot).
	if stats, err := s.q.GetCollectionStats(ctx, address); err == nil {
		res.FloorPriceWei = stats.FloorPriceWei
		res.Volume_24HWei = stats.Volume24hWei
		res.ListedCount = int32(stats.ListedCount)
	}

	return connect.NewResponse(res), nil
}

// ── ListListings (server-streaming) ──────────────────────────────────────────

func (s *Server) ListListings(ctx context.Context, req *connect.Request[ListListingsRequest], stream *connect.ServerStream[Listing]) error {
	f := db.ListingsFilter{
		Collection:  strings.ToLower(req.Msg.GetCollection()),
		Seller:      strings.ToLower(req.Msg.GetSeller()),
		Sort:        req.Msg.GetSort(),
		MinPriceWei: req.Msg.GetMinPriceWei(),
		MaxPriceWei: req.Msg.GetMaxPriceWei(),
	}
	if f.Sort == "" {
		f.Sort = "recent"
	}
	if limit := int(req.Msg.GetLimit()); limit > 0 && limit <= 100 {
		f.Limit = limit
	} else {
		f.Limit = 50
	}
	if traits := req.Msg.GetTraits(); traits != "" {
		f.Traits = make(map[string]string)
		for _, pair := range strings.Split(traits, ",") {
			parts := strings.SplitN(pair, ":", 2)
			if len(parts) == 2 && parts[0] != "" && parts[1] != "" {
				f.Traits[parts[0]] = parts[1]
			}
		}
	}

	rows, err := s.q.ListActiveListings(ctx, f)
	if err != nil {
		return connect.NewError(connect.CodeInternal, err)
	}

	for i := range rows {
		l := &Listing{
			Collection:         rows[i].Collection,
			TokenId:            rows[i].TokenID,
			Seller:             rows[i].Seller,
			PriceWei:           rows[i].PriceWei,
			Amount:             rows[i].Amount,
			Standard:           rows[i].Standard,
			TxHash:             rows[i].TxHash,
			Name:               rows[i].Name,
			ImageUri:           rows[i].ImageURI,
			CollectionVerified: rows[i].CollectionVerified,
		}
		if !rows[i].ExpiresAt.IsZero() {
			l.ExpiresAtMs = rows[i].ExpiresAt.UnixMilli()
		}
		if !rows[i].ListedAt.IsZero() {
			l.ListedAtMs = rows[i].ListedAt.UnixMilli()
		}
		if err := stream.Send(l); err != nil {
			return err
		}
	}
	return nil
}

// ── ListAuctions (server-streaming) ──────────────────────────────────────────

func (s *Server) ListAuctions(ctx context.Context, req *connect.Request[ListAuctionsRequest], stream *connect.ServerStream[Auction]) error {
	f := db.AuctionsFilter{
		Collection:  strings.ToLower(req.Msg.GetCollection()),
		Seller:      strings.ToLower(req.Msg.GetSeller()),
		Status:      req.Msg.GetStatus(),
		MinPriceWei: req.Msg.GetMinPriceWei(),
		MaxPriceWei: req.Msg.GetMaxPriceWei(),
	}
	if limit := int(req.Msg.GetLimit()); limit > 0 && limit <= 200 {
		f.Limit = limit
	} else {
		f.Limit = 50
	}

	rows, err := s.q.ListAuctions(ctx, f)
	if err != nil {
		return connect.NewError(connect.CodeInternal, err)
	}

	for i := range rows {
		a := &Auction{
			AuctionId:       rows[i].AuctionID,
			Collection:      rows[i].Collection,
			TokenId:         rows[i].TokenID,
			Seller:          rows[i].Seller,
			Standard:        rows[i].Standard,
			ReservePriceWei: rows[i].ReservePriceWei,
			HighestBidWei:   rows[i].HighestBidWei,
			HighestBidder:   rows[i].HighestBidder,
			MinIncrementBps: int32(rows[i].MinIncrementBps),
			Status:          rows[i].Status,
			CreateTx:        rows[i].CreateTx,
			Name:            rows[i].Name,
			ImageUri:        rows[i].ImageURI,
		}
		if !rows[i].StartsAt.IsZero() {
			a.StartsAtMs = rows[i].StartsAt.UnixMilli()
		}
		if !rows[i].EndsAt.IsZero() {
			a.EndsAtMs = rows[i].EndsAt.UnixMilli()
		}
		if err := stream.Send(a); err != nil {
			return err
		}
	}
	return nil
}

// ── GetActivity ──────────────────────────────────────────────────────────────

func (s *Server) GetActivity(ctx context.Context, req *connect.Request[GetActivityRequest]) (*connect.Response[GetActivityResponse], error) {
	limit := int(req.Msg.GetLimit())
	if limit <= 0 || limit > 200 {
		limit = 50
	}
	address := strings.ToLower(req.Msg.GetAddress())
	collection := strings.ToLower(req.Msg.GetCollection())
	tokenID := req.Msg.GetTokenId()

	var rows []db.ActivityRow
	var err error

	// Route to correct query based on filter params.
	switch {
	case collection != "" && tokenID != "" && address != "":
		tokenRows, terr := s.q.GetTokenActivityByAddress(ctx, collection, tokenID, address, limit)
		if terr != nil {
			return nil, connect.NewError(connect.CodeInternal, terr)
		}
		rows = tokenActivityToActivityRow(tokenRows, collection, tokenID)
	case collection != "" && tokenID != "":
		tokenRows, terr := s.q.GetTokenActivity(ctx, collection, tokenID, limit)
		if terr != nil {
			return nil, connect.NewError(connect.CodeInternal, terr)
		}
		rows = tokenActivityToActivityRow(tokenRows, collection, tokenID)
	case address != "":
		rows, err = s.q.GetRecentTransactionsByAddress(ctx, address, limit)
	default:
		rows, err = s.q.GetRecentTransactions(ctx, limit)
	}
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	events := make([]*ActivityEvent, 0, len(rows))
	for i := range rows {
		events = append(events, &ActivityEvent{
			Type:        rows[i].Type,
			Collection:  rows[i].Collection,
			TokenId:     rows[i].TokenID,
			AmountWei:   rows[i].AmountWei,
			TimestampMs: rows[i].Timestamp.UnixMilli(),
			TxHash:      rows[i].TxHash,
		})
	}
	if events == nil {
		events = []*ActivityEvent{}
	}

	return connect.NewResponse(&GetActivityResponse{Events: events}), nil
}

// ── ListOffers (server-streaming) ────────────────────────────────────────────

func (s *Server) ListOffers(ctx context.Context, req *connect.Request[ListOffersRequest], stream *connect.ServerStream[Offer]) error {
	f := db.OffersFilter{
		Collection: strings.ToLower(req.Msg.GetCollection()),
		TokenID:    req.Msg.GetTokenId(),
		Bidder:     strings.ToLower(req.Msg.GetBidder()),
		Owner:      strings.ToLower(req.Msg.GetOwner()),
		Status:     req.Msg.GetStatus(),
	}
	if limit := int(req.Msg.GetLimit()); limit > 0 && limit <= 100 {
		f.Limit = limit
	} else {
		f.Limit = 50
	}

	rows, err := s.q.ListOffers(ctx, f)
	if err != nil {
		return connect.NewError(connect.CodeInternal, err)
	}

	for i := range rows {
		if err := stream.Send(offerRowToProto(&rows[i])); err != nil {
			return err
		}
	}
	return nil
}

// ── GetWalletNFTs ─────────────────────────────────────────────────────────────

func (s *Server) GetWalletNFTs(ctx context.Context, req *connect.Request[GetWalletNFTsRequest]) (*connect.Response[GetWalletNFTsResponse], error) {
	owner := strings.ToLower(req.Msg.GetOwner())
	if owner == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, errString("owner address required"))
	}

	rows, err := s.q.WalletNFTs(ctx, owner)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	nfts := make([]*OwnedNFT, 0, len(rows))
	for i := range rows {
		nfts = append(nfts, &OwnedNFT{
			Collection: rows[i].Collection,
			TokenId:    rows[i].TokenID,
			Units:      rows[i].Units,
			Standard:   rows[i].Standard,
			Name:       rows[i].Name,
			ImageUri:   rows[i].ImageURI,
		})
	}
	if nfts == nil {
		nfts = []*OwnedNFT{}
	}

	return connect.NewResponse(&GetWalletNFTsResponse{Nfts: nfts}), nil
}

// ── GetProfile ────────────────────────────────────────────────────────────────

func (s *Server) GetProfile(ctx context.Context, req *connect.Request[GetProfileRequest]) (*connect.Response[GetProfileResponse], error) {
	address := strings.ToLower(req.Msg.GetAddress())
	if address == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, errString("address required"))
	}

	row, err := s.q.GetProfile(ctx, address)
	if err != nil {
		if isNotFound(err) {
			return nil, connect.NewError(connect.CodeNotFound, err)
		}
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	return connect.NewResponse(&GetProfileResponse{
		Address:     row.Address,
		DisplayName: row.DisplayName,
		Bio:         row.Bio,
		AvatarUri:   row.AvatarURI,
		BannerUri:   row.BannerURI,
		Twitter:     row.Twitter,
		Website:     row.Website,
		Verified:    row.Verified,
	}), nil
}

// ── Search ─────────────────────────────────────────────────────────────────────

func (s *Server) Search(ctx context.Context, req *connect.Request[SearchRequest]) (*connect.Response[SearchResponse], error) {
	query := strings.TrimSpace(req.Msg.GetQuery())
	if len(query) < 2 {
		return nil, connect.NewError(connect.CodeInvalidArgument, errString("query must be at least 2 characters"))
	}
	limit := int(req.Msg.GetLimit())
	if limit <= 0 || limit > 50 {
		limit = 20
	}

	rows, err := s.q.Search(ctx, query, limit)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	results := make([]*SearchResult, 0, len(rows))
	for i := range rows {
		results = append(results, &SearchResult{
			Kind:       rows[i].Kind,
			Collection: rows[i].Collection,
			TokenId:    rows[i].TokenID,
			Name:       rows[i].Name,
			ImageUri:   rows[i].ImageURI,
		})
	}
	if results == nil {
		results = []*SearchResult{}
	}

	return connect.NewResponse(&SearchResponse{Results: results}), nil
}

// ── GetMetrics ────────────────────────────────────────────────────────────────

func (s *Server) GetMetrics(ctx context.Context, req *connect.Request[GetMetricsRequest]) (*connect.Response[GetMetricsResponse], error) {
	m, err := s.q.GetMarketMetrics(ctx)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	if m == nil {
		m = &db.MarketMetrics{}
	}

	return connect.NewResponse(&GetMetricsResponse{
		TotalActiveListings: int32(m.TotalActiveListings),
		TotalSales:          int32(m.TotalSales),
		GrossVolumeWei:      m.GrossVolumeWei,
		TotalAuctions:       int32(m.TotalAuctions),
		TotalBids:           int32(m.TotalBids),
		TotalOffers:         int32(m.TotalOffers),
	}), nil
}

// ── Helpers ─────────────────────────────────────────────────────────────────

func isNotFound(err error) bool {
	if err == nil {
		return false
	}
	s := err.Error()
	return strings.Contains(s, "not found") || strings.Contains(s, "no rows")
}

func errString(msg string) error {
	return fmt.Errorf("%s", msg)
}

func tokenActivityToActivityRow(rows []db.TokenActivityRow, coll, tokID string) []db.ActivityRow {
	out := make([]db.ActivityRow, len(rows))
	for i, tr := range rows {
		out[i] = db.ActivityRow{
			Type: tr.Type, Collection: coll, TokenID: tokID,
			AmountWei: tr.AmountWei, Timestamp: tr.Timestamp, TxHash: tr.TxHash,
		}
	}
	return out
}

func offerRowToProto(row *db.OfferRow) *Offer {
	o := &Offer{
		OfferId:    row.OfferID,
		Bidder:     row.Bidder,
		Collection: row.Collection,
		TokenId:    row.TokenID,
		AmountWei:  row.AmountWei,
		FeeWei:     row.FeeWei,
		Units:      row.Units,
		Standard:   row.Standard,
		Status:     row.Status,
		MakeTx:     row.MakeTx,
	}
	if !row.ExpiresAt.IsZero() {
		o.ExpiresAtMs = row.ExpiresAt.UnixMilli()
	}
	if !row.CreatedAt.IsZero() {
		o.CreatedAtMs = row.CreatedAt.UnixMilli()
	}
	return o
}
