// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: election.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeeperElection_Heartbeat_FullMethodName = "/keeper.KeeperElection/Heartbeat"
)

// KeeperElectionClient is the client API for KeeperElection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeeperElection is a unary RPC service for cluster-wide leader election.
// Every instance in the cluster registers a server and connects a client
// to every peer. The lowest-addressed instance (lexicographic on address)
// is the initial leader. Leader sends heartbeats every 1s; any follower
// that misses 3 consecutive heartbeats declares itself leader.
type KeeperElectionClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type keeperElectionClient struct {
	cc grpc.ClientConnInterface
}

func NewKeeperElectionClient(cc grpc.ClientConnInterface) KeeperElectionClient {
	return &keeperElectionClient{cc}
}

func (c *keeperElectionClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, KeeperElection_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeeperElectionServer is the server API for KeeperElection service.
// All implementations must embed UnimplementedKeeperElectionServer
// for forward compatibility.
//
// KeeperElection is a unary RPC service for cluster-wide leader election.
// Every instance in the cluster registers a server and connects a client
// to every peer. The lowest-addressed instance (lexicographic on address)
// is the initial leader. Leader sends heartbeats every 1s; any follower
// that misses 3 consecutive heartbeats declares itself leader.
type KeeperElectionServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedKeeperElectionServer()
}

// UnimplementedKeeperElectionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeeperElectionServer struct{}

func (UnimplementedKeeperElectionServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedKeeperElectionServer) mustEmbedUnimplementedKeeperElectionServer() {}
func (UnimplementedKeeperElectionServer) testEmbeddedByValue()                        {}

// UnsafeKeeperElectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeeperElectionServer will
// result in compilation errors.
type UnsafeKeeperElectionServer interface {
	mustEmbedUnimplementedKeeperElectionServer()
}

func RegisterKeeperElectionServer(s grpc.ServiceRegistrar, srv KeeperElectionServer) {
	// If the following call panics, it indicates UnimplementedKeeperElectionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeeperElection_ServiceDesc, srv)
}

func _KeeperElection_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperElectionServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeeperElection_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperElectionServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeeperElection_ServiceDesc is the grpc.ServiceDesc for KeeperElection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeeperElection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keeper.KeeperElection",
	HandlerType: (*KeeperElectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _KeeperElection_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "election.proto",
}
