// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ActivityItem struct {
	Type       string  `json:"type"`
	Collection string  `json:"collection"`
	TokenID    string  `json:"tokenId"`
	Actor      *string `json:"actor,omitempty"`
	AmountWei  *string `json:"amountWei,omitempty"`
	TxHash     string  `json:"txHash"`
	Timestamp  int     `json:"timestamp"`
}

type AuctionEvent struct {
	Type       string  `json:"type"`
	AuctionID  string  `json:"auctionId"`
	Collection string  `json:"collection"`
	TokenID    string  `json:"tokenId"`
	Bidder     *string `json:"bidder,omitempty"`
	AmountWei  *string `json:"amountWei,omitempty"`
	TxHash     string  `json:"txHash"`
	Timestamp  int     `json:"timestamp"`
}

type AuctionItem struct {
	AuctionID     string `json:"auctionId"`
	Collection    string `json:"collection"`
	TokenID       string `json:"tokenId"`
	Seller        string `json:"seller"`
	ReserveWei    string `json:"reserveWei"`
	HighestBidWei string `json:"highestBidWei"`
	EndsAt        int    `json:"endsAt"`
	Status        string `json:"status"`
}

type ListingEvent struct {
	Type       string  `json:"type"`
	Collection string  `json:"collection"`
	TokenID    string  `json:"tokenId"`
	Seller     *string `json:"seller,omitempty"`
	Buyer      *string `json:"buyer,omitempty"`
	PriceWei   *string `json:"priceWei,omitempty"`
	TxHash     string  `json:"txHash"`
	Timestamp  int     `json:"timestamp"`
}

type ListingItem struct {
	Collection string `json:"collection"`
	TokenID    string `json:"tokenId"`
	Seller     string `json:"seller"`
	PriceWei   string `json:"priceWei"`
	ExpiresAt  int    `json:"expiresAt"`
}

type MarketMetrics struct {
	TotalActiveListings int    `json:"totalActiveListings"`
	TotalSales          int    `json:"totalSales"`
	GrossVolumeWei      string `json:"grossVolumeWei"`
	TotalAuctions       int    `json:"totalAuctions"`
}

type OfferEvent struct {
	Type       string  `json:"type"`
	Collection string  `json:"collection"`
	TokenID    *string `json:"tokenId,omitempty"`
	Bidder     string  `json:"bidder"`
	AmountWei  string  `json:"amountWei"`
	Nonce      string  `json:"nonce"`
	TxHash     *string `json:"txHash,omitempty"`
	Timestamp  int     `json:"timestamp"`
}

type Query struct {
}

type Subscription struct {
}
