// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: events.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventBridge_StreamEvents_FullMethodName = "/sse.EventBridge/StreamEvents"
)

// EventBridgeClient is the client API for EventBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventBridge is a bidirectional streaming RPC. Each instance opens a single
// persistent stream to every peer. Both sides send EventMessages — the stream
// is bidirectional so each instance can both publish to and receive from every
// peer over a single TCP connection.
type EventBridgeClient interface {
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventMessage, EventMessage], error)
}

type eventBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewEventBridgeClient(cc grpc.ClientConnInterface) EventBridgeClient {
	return &eventBridgeClient{cc}
}

func (c *eventBridgeClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventMessage, EventMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventBridge_ServiceDesc.Streams[0], EventBridge_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventMessage, EventMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventBridge_StreamEventsClient = grpc.BidiStreamingClient[EventMessage, EventMessage]

// EventBridgeServer is the server API for EventBridge service.
// All implementations must embed UnimplementedEventBridgeServer
// for forward compatibility.
//
// EventBridge is a bidirectional streaming RPC. Each instance opens a single
// persistent stream to every peer. Both sides send EventMessages — the stream
// is bidirectional so each instance can both publish to and receive from every
// peer over a single TCP connection.
type EventBridgeServer interface {
	StreamEvents(grpc.BidiStreamingServer[EventMessage, EventMessage]) error
	mustEmbedUnimplementedEventBridgeServer()
}

// UnimplementedEventBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventBridgeServer struct{}

func (UnimplementedEventBridgeServer) StreamEvents(grpc.BidiStreamingServer[EventMessage, EventMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEventBridgeServer) mustEmbedUnimplementedEventBridgeServer() {}
func (UnimplementedEventBridgeServer) testEmbeddedByValue()                     {}

// UnsafeEventBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventBridgeServer will
// result in compilation errors.
type UnsafeEventBridgeServer interface {
	mustEmbedUnimplementedEventBridgeServer()
}

func RegisterEventBridgeServer(s grpc.ServiceRegistrar, srv EventBridgeServer) {
	// If the following call panics, it indicates UnimplementedEventBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventBridge_ServiceDesc, srv)
}

func _EventBridge_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventBridgeServer).StreamEvents(&grpc.GenericServerStream[EventMessage, EventMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventBridge_StreamEventsServer = grpc.BidiStreamingServer[EventMessage, EventMessage]

// EventBridge_ServiceDesc is the grpc.ServiceDesc for EventBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sse.EventBridge",
	HandlerType: (*EventBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventBridge_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "events.proto",
}
