// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: marketplace/v1/marketplace.proto

package marketplacev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	marketplacev1 "github.com/OfficialA1manac/MagicWebb/backend/internal/connectrpc/marketplacev1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MarketplaceServiceName is the fully-qualified name of the MarketplaceService service.
	MarketplaceServiceName = "marketplace.v1.MarketplaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MarketplaceServiceGetListingProcedure is the fully-qualified name of the MarketplaceService's
	// GetListing RPC.
	MarketplaceServiceGetListingProcedure = "/marketplace.v1.MarketplaceService/GetListing"
	// MarketplaceServiceGetAuctionProcedure is the fully-qualified name of the MarketplaceService's
	// GetAuction RPC.
	MarketplaceServiceGetAuctionProcedure = "/marketplace.v1.MarketplaceService/GetAuction"
	// MarketplaceServiceGetOfferProcedure is the fully-qualified name of the MarketplaceService's
	// GetOffer RPC.
	MarketplaceServiceGetOfferProcedure = "/marketplace.v1.MarketplaceService/GetOffer"
	// MarketplaceServiceGetTokenProcedure is the fully-qualified name of the MarketplaceService's
	// GetToken RPC.
	MarketplaceServiceGetTokenProcedure = "/marketplace.v1.MarketplaceService/GetToken"
)

// MarketplaceServiceClient is a client for the marketplace.v1.MarketplaceService service.
type MarketplaceServiceClient interface {
	// GetListing returns the current active listing for a token.
	GetListing(context.Context, *connect.Request[marketplacev1.GetListingRequest]) (*connect.Response[marketplacev1.GetListingResponse], error)
	// GetAuction returns auction state by auction ID.
	GetAuction(context.Context, *connect.Request[marketplacev1.GetAuctionRequest]) (*connect.Response[marketplacev1.GetAuctionResponse], error)
	// GetOffer returns an offer by its on-chain ID.
	GetOffer(context.Context, *connect.Request[marketplacev1.GetOfferRequest]) (*connect.Response[marketplacev1.GetOfferResponse], error)
	// GetToken returns full on-chain metadata for a token.
	GetToken(context.Context, *connect.Request[marketplacev1.GetTokenRequest]) (*connect.Response[marketplacev1.GetTokenResponse], error)
}

// NewMarketplaceServiceClient constructs a client for the marketplace.v1.MarketplaceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMarketplaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MarketplaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	marketplaceServiceMethods := marketplacev1.File_marketplace_v1_marketplace_proto.Services().ByName("MarketplaceService").Methods()
	return &marketplaceServiceClient{
		getListing: connect.NewClient[marketplacev1.GetListingRequest, marketplacev1.GetListingResponse](
			httpClient,
			baseURL+MarketplaceServiceGetListingProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("GetListing")),
			connect.WithClientOptions(opts...),
		),
		getAuction: connect.NewClient[marketplacev1.GetAuctionRequest, marketplacev1.GetAuctionResponse](
			httpClient,
			baseURL+MarketplaceServiceGetAuctionProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("GetAuction")),
			connect.WithClientOptions(opts...),
		),
		getOffer: connect.NewClient[marketplacev1.GetOfferRequest, marketplacev1.GetOfferResponse](
			httpClient,
			baseURL+MarketplaceServiceGetOfferProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("GetOffer")),
			connect.WithClientOptions(opts...),
		),
		getToken: connect.NewClient[marketplacev1.GetTokenRequest, marketplacev1.GetTokenResponse](
			httpClient,
			baseURL+MarketplaceServiceGetTokenProcedure,
			connect.WithSchema(marketplaceServiceMethods.ByName("GetToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// marketplaceServiceClient implements MarketplaceServiceClient.
type marketplaceServiceClient struct {
	getListing *connect.Client[marketplacev1.GetListingRequest, marketplacev1.GetListingResponse]
	getAuction *connect.Client[marketplacev1.GetAuctionRequest, marketplacev1.GetAuctionResponse]
	getOffer   *connect.Client[marketplacev1.GetOfferRequest, marketplacev1.GetOfferResponse]
	getToken   *connect.Client[marketplacev1.GetTokenRequest, marketplacev1.GetTokenResponse]
}

// GetListing calls marketplace.v1.MarketplaceService.GetListing.
func (c *marketplaceServiceClient) GetListing(ctx context.Context, req *connect.Request[marketplacev1.GetListingRequest]) (*connect.Response[marketplacev1.GetListingResponse], error) {
	return c.getListing.CallUnary(ctx, req)
}

// GetAuction calls marketplace.v1.MarketplaceService.GetAuction.
func (c *marketplaceServiceClient) GetAuction(ctx context.Context, req *connect.Request[marketplacev1.GetAuctionRequest]) (*connect.Response[marketplacev1.GetAuctionResponse], error) {
	return c.getAuction.CallUnary(ctx, req)
}

// GetOffer calls marketplace.v1.MarketplaceService.GetOffer.
func (c *marketplaceServiceClient) GetOffer(ctx context.Context, req *connect.Request[marketplacev1.GetOfferRequest]) (*connect.Response[marketplacev1.GetOfferResponse], error) {
	return c.getOffer.CallUnary(ctx, req)
}

// GetToken calls marketplace.v1.MarketplaceService.GetToken.
func (c *marketplaceServiceClient) GetToken(ctx context.Context, req *connect.Request[marketplacev1.GetTokenRequest]) (*connect.Response[marketplacev1.GetTokenResponse], error) {
	return c.getToken.CallUnary(ctx, req)
}

// MarketplaceServiceHandler is an implementation of the marketplace.v1.MarketplaceService service.
type MarketplaceServiceHandler interface {
	// GetListing returns the current active listing for a token.
	GetListing(context.Context, *connect.Request[marketplacev1.GetListingRequest]) (*connect.Response[marketplacev1.GetListingResponse], error)
	// GetAuction returns auction state by auction ID.
	GetAuction(context.Context, *connect.Request[marketplacev1.GetAuctionRequest]) (*connect.Response[marketplacev1.GetAuctionResponse], error)
	// GetOffer returns an offer by its on-chain ID.
	GetOffer(context.Context, *connect.Request[marketplacev1.GetOfferRequest]) (*connect.Response[marketplacev1.GetOfferResponse], error)
	// GetToken returns full on-chain metadata for a token.
	GetToken(context.Context, *connect.Request[marketplacev1.GetTokenRequest]) (*connect.Response[marketplacev1.GetTokenResponse], error)
}

// NewMarketplaceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMarketplaceServiceHandler(svc MarketplaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	marketplaceServiceMethods := marketplacev1.File_marketplace_v1_marketplace_proto.Services().ByName("MarketplaceService").Methods()
	marketplaceServiceGetListingHandler := connect.NewUnaryHandler(
		MarketplaceServiceGetListingProcedure,
		svc.GetListing,
		connect.WithSchema(marketplaceServiceMethods.ByName("GetListing")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceGetAuctionHandler := connect.NewUnaryHandler(
		MarketplaceServiceGetAuctionProcedure,
		svc.GetAuction,
		connect.WithSchema(marketplaceServiceMethods.ByName("GetAuction")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceGetOfferHandler := connect.NewUnaryHandler(
		MarketplaceServiceGetOfferProcedure,
		svc.GetOffer,
		connect.WithSchema(marketplaceServiceMethods.ByName("GetOffer")),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceGetTokenHandler := connect.NewUnaryHandler(
		MarketplaceServiceGetTokenProcedure,
		svc.GetToken,
		connect.WithSchema(marketplaceServiceMethods.ByName("GetToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/marketplace.v1.MarketplaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MarketplaceServiceGetListingProcedure:
			marketplaceServiceGetListingHandler.ServeHTTP(w, r)
		case MarketplaceServiceGetAuctionProcedure:
			marketplaceServiceGetAuctionHandler.ServeHTTP(w, r)
		case MarketplaceServiceGetOfferProcedure:
			marketplaceServiceGetOfferHandler.ServeHTTP(w, r)
		case MarketplaceServiceGetTokenProcedure:
			marketplaceServiceGetTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMarketplaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMarketplaceServiceHandler struct{}

func (UnimplementedMarketplaceServiceHandler) GetListing(context.Context, *connect.Request[marketplacev1.GetListingRequest]) (*connect.Response[marketplacev1.GetListingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("marketplace.v1.MarketplaceService.GetListing is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) GetAuction(context.Context, *connect.Request[marketplacev1.GetAuctionRequest]) (*connect.Response[marketplacev1.GetAuctionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("marketplace.v1.MarketplaceService.GetAuction is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) GetOffer(context.Context, *connect.Request[marketplacev1.GetOfferRequest]) (*connect.Response[marketplacev1.GetOfferResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("marketplace.v1.MarketplaceService.GetOffer is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) GetToken(context.Context, *connect.Request[marketplacev1.GetTokenRequest]) (*connect.Response[marketplacev1.GetTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("marketplace.v1.MarketplaceService.GetToken is not implemented"))
}
