package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/OfficialA1manac/MagicWebb/backend/graph/generated"
	"github.com/OfficialA1manac/MagicWebb/backend/graph/model"
	"github.com/OfficialA1manac/MagicWebb/backend/internal/db"
)

// ── Query resolvers ───────────────────────────────────────────────────────────

// Listings is the resolver for the listings field.
func (r *queryResolver) Listings(ctx context.Context, collection *string, limit *int) ([]*model.ListingItem, error) {
	f := db.ListingsFilter{Limit: 50}
	if collection != nil {
		f.Collection = *collection
	}
	if limit != nil && *limit > 0 {
		f.Limit = *limit
	}
	rows, err := r.Q.ListActiveListings(ctx, f)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ListingItem, len(rows))
	for i, row := range rows {
		out[i] = &model.ListingItem{
			Collection: row.Collection,
			TokenID:    row.TokenID,
			Seller:     row.Seller,
			PriceWei:   row.PriceWei,
			ExpiresAt:  int(row.ExpiresAt.Unix()),
		}
	}
	return out, nil
}

// Auctions is the resolver for the auctions field.
func (r *queryResolver) Auctions(ctx context.Context, status *string, limit *int) ([]*model.AuctionItem, error) {
	f := db.AuctionsFilter{Limit: 50}
	if status != nil {
		f.Status = *status
	}
	if limit != nil && *limit > 0 {
		f.Limit = *limit
	}
	rows, err := r.Q.ListAuctions(ctx, f)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AuctionItem, len(rows))
	for i, row := range rows {
		out[i] = &model.AuctionItem{
			AuctionID:     strconv.FormatInt(row.AuctionID, 10),
			Collection:    row.Collection,
			TokenID:       row.TokenID,
			Seller:        row.Seller,
			ReserveWei:    row.ReservePriceWei,
			HighestBidWei: row.HighestBidWei,
			EndsAt:        int(row.EndsAt.Unix()),
			Status:        row.Status,
		}
	}
	return out, nil
}

// MarketMetrics is the resolver for the marketMetrics field.
func (r *queryResolver) MarketMetrics(ctx context.Context) (*model.MarketMetrics, error) {
	m, err := r.Q.GetMarketMetrics(ctx)
	if err != nil {
		return nil, err
	}
	return &model.MarketMetrics{
		TotalActiveListings: int(m.TotalActiveListings),
		TotalSales:          int(m.TotalSales),
		GrossVolumeWei:      m.GrossVolumeWei,
		TotalAuctions:       int(m.TotalAuctions),
	}, nil
}

// ActivityFeed is the resolver for the activityFeed query field.
func (r *queryResolver) ActivityFeed(ctx context.Context, limit *int) ([]*model.ActivityItem, error) {
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	rows, err := r.Q.GetRecentTransactions(ctx, lim)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ActivityItem, len(rows))
	for i, row := range rows {
		out[i] = &model.ActivityItem{
			Type:       row.Type,
			Collection: row.Collection,
			TokenID:    row.TokenID,
			AmountWei:  ptr(row.AmountWei),
			TxHash:     row.TxHash,
			Timestamp:  int(row.Timestamp.Unix()),
		}
	}
	return out, nil
}

// ── Subscription resolvers ────────────────────────────────────────────────────

// ListingEvents is the resolver for the listingEvents field.
func (r *subscriptionResolver) ListingEvents(ctx context.Context) (<-chan *model.ListingEvent, error) {
	ch := make(chan *model.ListingEvent, 16)
	msgs := r.RDB.SubscribeMessages(ctx, "mktplace:events")
	go func() {
		defer close(ch)
		for payload := range msgs {
			var ev model.ListingEvent
			if err := json.Unmarshal([]byte(payload), &ev); err != nil {
				continue
			}
			select {
			case ch <- &ev:
			case <-ctx.Done():
				return
			}
		}
	}()
	return ch, nil
}

// AuctionEvents is the resolver for the auctionEvents field.
func (r *subscriptionResolver) AuctionEvents(ctx context.Context) (<-chan *model.AuctionEvent, error) {
	ch := make(chan *model.AuctionEvent, 16)
	msgs := r.RDB.SubscribeMessages(ctx, "auction:events")
	go func() {
		defer close(ch)
		for payload := range msgs {
			var ev model.AuctionEvent
			if err := json.Unmarshal([]byte(payload), &ev); err != nil {
				continue
			}
			select {
			case ch <- &ev:
			case <-ctx.Done():
				return
			}
		}
	}()
	return ch, nil
}

// OfferEvents is the resolver for the offerEvents field.
func (r *subscriptionResolver) OfferEvents(ctx context.Context) (<-chan *model.OfferEvent, error) {
	ch := make(chan *model.OfferEvent, 16)
	msgs := r.RDB.SubscribeMessages(ctx, "offers:events")
	go func() {
		defer close(ch)
		for payload := range msgs {
			var ev model.OfferEvent
			if err := json.Unmarshal([]byte(payload), &ev); err != nil {
				continue
			}
			select {
			case ch <- &ev:
			case <-ctx.Done():
				return
			}
		}
	}()
	return ch, nil
}

// ActivityFeed is the resolver for the activityFeed subscription field.
// Fans in all 3 event channels and emits ActivityItem.
func (r *subscriptionResolver) ActivityFeed(ctx context.Context) (<-chan *model.ActivityItem, error) {
	ch := make(chan *model.ActivityItem, 64)
	mkting := r.RDB.SubscribeMessages(ctx, "mktplace:events")
	auction := r.RDB.SubscribeMessages(ctx, "auction:events")
	offers := r.RDB.SubscribeMessages(ctx, "offers:events")

	go func() {
		defer close(ch)
		done := ctx.Done()
		for {
			select {
			case p, ok := <-mkting:
				if !ok {
					mkting = nil
				} else {
					var raw map[string]any
					if err := json.Unmarshal([]byte(p), &raw); err == nil {
						select {
						case ch <- activityFromRaw(raw, "listing"):
						case <-done:
							return
						}
					}
				}
			case p, ok := <-auction:
				if !ok {
					auction = nil
				} else {
					var raw map[string]any
					if err := json.Unmarshal([]byte(p), &raw); err == nil {
						select {
						case ch <- activityFromRaw(raw, "auction"):
						case <-done:
							return
						}
					}
				}
			case p, ok := <-offers:
				if !ok {
					offers = nil
				} else {
					var raw map[string]any
					if err := json.Unmarshal([]byte(p), &raw); err == nil {
						select {
						case ch <- activityFromRaw(raw, "offer"):
						case <-done:
							return
						}
					}
				}
			case <-done:
				return
			}
			if mkting == nil && auction == nil && offers == nil {
				return
			}
		}
	}()
	return ch, nil
}

// ── helpers ───────────────────────────────────────────────────────────────────

func activityFromRaw(raw map[string]any, srcType string) *model.ActivityItem {
	str := func(key string) string {
		if v, ok := raw[key].(string); ok {
			return v
		}
		return ""
	}
	strPtr := func(key string) *string {
		if v, ok := raw[key].(string); ok && v != "" {
			return &v
		}
		return nil
	}
	ts := 0
	if v, ok := raw["timestamp"]; ok {
		switch t := v.(type) {
		case float64:
			ts = int(t)
		case json.Number:
			if n, err := t.Int64(); err == nil {
				ts = int(n)
			}
		}
	}
	typ := str("type")
	if typ == "" {
		typ = srcType
	}
	collection := str("collection")
	if collection == "" {
		collection = str("Collection")
	}
	tokenId := str("tokenId")
	if tokenId == "" {
		tokenId = str("token_id")
	}
	txHash := str("txHash")
	if txHash == "" {
		txHash = str("tx_hash")
	}
	return &model.ActivityItem{
		Type:       typ,
		Collection: collection,
		TokenID:    tokenId,
		Actor:      strPtr("seller"),
		AmountWei:  strPtr("priceWei"),
		TxHash:     txHash,
		Timestamp:  ts,
	}
}

func ptr(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}

// ── Resolver type aliases (required by generated code) ───────────────────────

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// Ensure interface compliance at compile time.
var _ generated.QueryResolver = (*queryResolver)(nil)
var _ generated.SubscriptionResolver = (*subscriptionResolver)(nil)

// suppress fmt import if unused in some build configs
var _ = fmt.Sprintf
