// Regenerates app/src/lib/abi/*.ts from Foundry artifacts in contracts/out.
// Run: npm run gen:abi   (after `forge build` in contracts/)
// Only functions/events/errors are kept; constructor + receive/fallback dropped.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..');
const out = resolve(root, 'contracts', 'out');
const dest = resolve(here, '..', 'src', 'lib', 'abi');
mkdirSync(dest, { recursive: true });

const targets = [
  ['Marketplace', 'Marketplace.sol/Marketplace.json', 'marketplace'],
  ['AuctionHouse', 'AuctionHouse.sol/AuctionHouse.json', 'auctionHouse'],
  ['OfferBook', 'OfferBook.sol/OfferBook.json', 'offerBook'],
  ['MarketplaceCore', 'MarketplaceCore.sol/MarketplaceCore.json', 'core'],
  ['MarketplaceManager', 'MarketplaceManager.sol/MarketplaceManager.json', 'manager'],
];

for (const [name, file, stem] of targets) {
  const art = JSON.parse(readFileSync(resolve(out, file), 'utf8'));
  const abi = art.abi.filter((e) => ['function', 'event', 'error'].includes(e.type));
  const body = `// AUTO-GENERATED by app/scripts/gen-abi.mjs from contracts/out/${file}. Do not edit.\n` +
    `export const ${stem}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(resolve(dest, `${stem}.ts`), body);
  console.log(`${name}: ${abi.length} entries → abi/${stem}.ts`);
}

// Minimal ERC-721 / ERC-1155 operator-approval + ownership ABIs (stable standards).
writeFileSync(resolve(dest, 'erc721.ts'), `// Minimal ERC-721 surface used by the marketplace UI.
export const erc721Abi = [
  { type: 'function', name: 'ownerOf', stateMutability: 'view', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ name: '', type: 'address' }] },
  { type: 'function', name: 'tokenURI', stateMutability: 'view', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ name: '', type: 'string' }] },
  { type: 'function', name: 'isApprovedForAll', stateMutability: 'view', inputs: [{ name: 'owner', type: 'address' }, { name: 'operator', type: 'address' }], outputs: [{ name: '', type: 'bool' }] },
  { type: 'function', name: 'setApprovalForAll', stateMutability: 'nonpayable', inputs: [{ name: 'operator', type: 'address' }, { name: 'approved', type: 'bool' }], outputs: [] },
  { type: 'function', name: 'supportsInterface', stateMutability: 'view', inputs: [{ name: 'interfaceId', type: 'bytes4' }], outputs: [{ name: '', type: 'bool' }] },
  // ERC-173 contract ownership. Not part of ERC-721 proper, but OfferBook's
  // setOfferEligible gates on it, so the UI reads it to decide whether the
  // connected wallet may enable offers. Contracts without it simply revert
  // the read and the caller treats ownership as unknown.
  { type: 'function', name: 'owner', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
] as const;
`);
writeFileSync(resolve(dest, 'erc1155.ts'), `// Minimal ERC-1155 surface used by the marketplace UI.
export const erc1155Abi = [
  { type: 'function', name: 'balanceOf', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }, { name: 'id', type: 'uint256' }], outputs: [{ name: '', type: 'uint256' }] },
  { type: 'function', name: 'isApprovedForAll', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }, { name: 'operator', type: 'address' }], outputs: [{ name: '', type: 'bool' }] },
  { type: 'function', name: 'setApprovalForAll', stateMutability: 'nonpayable', inputs: [{ name: 'operator', type: 'address' }, { name: 'approved', type: 'bool' }], outputs: [] },
  { type: 'function', name: 'supportsInterface', stateMutability: 'view', inputs: [{ name: 'interfaceId', type: 'bytes4' }], outputs: [{ name: '', type: 'bool' }] },
] as const;
`);
writeFileSync(resolve(dest, 'index.ts'), `export { marketplaceAbi } from './marketplace';
export { auctionHouseAbi } from './auctionHouse';
export { offerBookAbi } from './offerBook';
export { coreAbi } from './core';
export { managerAbi } from './manager';
export { erc721Abi } from './erc721';
export { erc1155Abi } from './erc1155';
`);
console.log('erc721/erc1155/index written');
